<?php

namespace Database\Seeders;

use App\Models\TeacherStaff;
use App\Models\School;
use Illuminate\Database\Seeder;

class TeacherStaffSeeder extends Seeder
{
    public function run(): void
    {
        $smk     = School::where('slug', 'smk-putra-pakuan')->first();
        $smp     = School::where('slug', 'smp-putra-pakuan')->first();
        $sdit    = School::where('slug', 'sdit-putra-pakuan')->first();
        $yayasan = School::where('slug', 'yayasan-putra-pakuan')->first();

        // Unsplash portrait photos — real, professional faces (consistently used)
        $photos = [
            'man_1'   => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
            'man_2'   => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
            'man_3'   => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80',
            'man_4'   => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
            'man_5'   => 'https://images.unsplash.com/photo-1554384645-13eab165c24b?w=400&q=80',
            'man_6'   => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
            'woman_1' => 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&q=80',
            'woman_2' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
            'woman_3' => 'https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=400&q=80',
            'woman_4' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&q=80',
            'woman_5' => 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&q=80',
            'woman_6' => 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&q=80',
        ];

        $staff = [
            // ─── SMK — Kepala Sekolah & Wakasek ────────────────────────────
            [
                'school_id'  => $smk->id,
                'name'       => 'Drs. Ahmad Sujana, M.Pd.',
                'title'      => 'Kepala Sekolah',
                'department' => 'Pimpinan',
                'type'       => 'teacher',
                'bio'        => 'Berpengalaman lebih dari 25 tahun di bidang pendidikan vokasi. Lulusan S2 Manajemen Pendidikan Universitas Pakuan.',
                'photo_url'  => $photos['man_1'],
                'email'      => 'kepala@smk-putrapakuan.sch.id',
                'sort_order' => 1,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smk->id,
                'name'       => 'Hendra Setiawan, S.T., M.Kom.',
                'title'      => 'Wakasek Bidang Kurikulum',
                'department' => 'Kurikulum',
                'type'       => 'teacher',
                'bio'        => 'Guru pengampu Jaringan Komputer sekaligus pembina olimpiade LKS. Pemegang sertifikasi Cisco CCNP.',
                'photo_url'  => $photos['man_2'],
                'email'      => 'hendra@smk-putrapakuan.sch.id',
                'sort_order' => 2,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smk->id,
                'name'       => 'Ir. Sugeng Prayitno, S.T.',
                'title'      => 'Ketua Kompetensi Keahlian TKRO',
                'department' => 'Teknik Kendaraan Ringan Otomotif',
                'type'       => 'teacher',
                'bio'        => 'Mantan teknisi PT. Toyota Astra Motor selama 10 tahun sebelum beralih ke dunia pendidikan. Aktif membina siswa untuk kompetisi otomotif.',
                'photo_url'  => $photos['man_3'],
                'email'      => 'sugeng@smk-putrapakuan.sch.id',
                'sort_order' => 3,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smk->id,
                'name'       => 'Dewi Ratnasari, S.Pd.',
                'title'      => 'Guru Bahasa Indonesia & Wali Kelas XII TKJ 1',
                'department' => 'Bahasa & Sastra',
                'type'       => 'teacher',
                'bio'        => 'Pendidik berdedikasi dengan spesialisasi literasi dan penulisan kreatif. Aktif membimbing ekstrakurikuler jurnalistik sekolah.',
                'photo_url'  => $photos['woman_1'],
                'email'      => 'dewi@smk-putrapakuan.sch.id',
                'sort_order' => 4,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smk->id,
                'name'       => 'Rizky Ananda, S.Kom.',
                'title'      => 'Guru Pemrograman Web & Basis Data',
                'department' => 'Teknik Jaringan Komputer & Telekomunikasi',
                'type'       => 'teacher',
                'bio'        => 'Pengembang web profesional yang juga mengajar di SMK. Aktif berkontribusi pada proyek open-source dan membimbing siswa dalam kompetisi coding.',
                'photo_url'  => $photos['man_4'],
                'email'      => 'rizky@smk-putrapakuan.sch.id',
                'sort_order' => 5,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smk->id,
                'name'       => 'Laila Fitriani, S.E.',
                'title'      => 'Kepala Tata Usaha',
                'department' => 'Administrasi',
                'type'       => 'staff',
                'bio'        => 'Bertanggung jawab atas seluruh administrasi sekolah. Telah mengabdi di SMK Putra Pakuan selama 15 tahun.',
                'photo_url'  => $photos['woman_2'],
                'email'      => 'tu@smk-putrapakuan.sch.id',
                'sort_order' => 6,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smk->id,
                'name'       => 'Budi Santoso, S.Pd.',
                'title'      => 'Guru Pendidikan Agama Islam & Budi Pekerti',
                'department' => 'Keagamaan',
                'type'       => 'teacher',
                'bio'        => 'Pembimbing rohani dan spiritual sekolah. Aktif mengorganisasi kegiatan keagamaan dan pesantren kilat.',
                'photo_url'  => $photos['man_5'],
                'email'      => 'budi@smk-putrapakuan.sch.id',
                'sort_order' => 7,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smk->id,
                'name'       => 'Sari Indrawati, S.Pd.',
                'title'      => 'Guru Matematika & Koordinator Ekstrakurikuler',
                'department' => 'Matematika & Sains',
                'type'       => 'teacher',
                'bio'        => 'Pengajar matematika yang dikenal kreatif dengan pendekatan gamifikasi dalam pembelajaran. Koordinator 12 ekstrakurikuler aktif di sekolah.',
                'photo_url'  => $photos['woman_3'],
                'email'      => 'sari@smk-putrapakuan.sch.id',
                'sort_order' => 8,
                'status'     => 'active',
            ],

            // ─── SMP ───────────────────────────────────────────────────────
            [
                'school_id'  => $smp->id,
                'name'       => 'Dra. Sri Mulyani, M.Pd.',
                'title'      => 'Kepala Sekolah',
                'department' => 'Pimpinan',
                'type'       => 'teacher',
                'bio'        => 'Pemimpin visioner dengan pengalaman panjang di bidang pendidikan menengah pertama. Peraih penghargaan Kepala Sekolah Inovatif tingkat Kabupaten Bogor 2024.',
                'photo_url'  => $photos['woman_4'],
                'email'      => 'kepsek@smp-putrapakuan.sch.id',
                'sort_order' => 1,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smp->id,
                'name'       => 'Irfan Maulana, S.Pd., M.Si.',
                'title'      => 'Wakasek Bidang Akademik & Pembina Olimpiade Matematika',
                'department' => 'Matematika',
                'type'       => 'teacher',
                'bio'        => 'Lulusan S2 Matematika LIPI. Berhasil membawa tiga siswa meraih medali dalam Olimpiade Matematika Kabupaten Bogor 2026. Mengajar dengan metode problem-solving yang sistematis.',
                'photo_url'  => $photos['man_6'],
                'email'      => 'irfan@smp-putrapakuan.sch.id',
                'sort_order' => 2,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smp->id,
                'name'       => 'Nuraini Kusuma, S.Pd.',
                'title'      => 'Guru Bahasa Inggris & Pembina Debat',
                'department' => 'Bahasa Inggris',
                'type'       => 'teacher',
                'bio'        => 'Pemegang sertifikasi TESOL/TEFL internasional. Aktif membimbing tim debat bahasa Inggris sekolah yang berhasil meraih juara tingkat Bogor Raya.',
                'photo_url'  => $photos['woman_5'],
                'email'      => 'nuraini@smp-putrapakuan.sch.id',
                'sort_order' => 3,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smp->id,
                'name'       => 'Rian Permana, S.Pd.',
                'title'      => 'Guru PJOK & Pembina Pramuka',
                'department' => 'Pendidikan Jasmani',
                'type'       => 'teacher',
                'bio'        => 'Mantan atlet bulu tangkis tingkat provinsi. Kini berdedikasi melatih siswa di bidang olahraga dan kepramukaan. Pembina Gugus Depan Pramuka SMP Putra Pakuan.',
                'photo_url'  => $photos['man_1'],
                'email'      => 'rian@smp-putrapakuan.sch.id',
                'sort_order' => 4,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smp->id,
                'name'       => 'Wulandari, S.Sn.',
                'title'      => 'Guru Seni Budaya & Prakarya',
                'department' => 'Seni Budaya',
                'type'       => 'teacher',
                'bio'        => 'Seniman dan pendidik yang pasionat. Pembina tim tari kreasi sekolah yang berhasil meraih Juara 1 Festival Seni Pelajar Kabupaten Bogor 2025.',
                'photo_url'  => $photos['woman_6'],
                'email'      => 'wulan@smp-putrapakuan.sch.id',
                'sort_order' => 5,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smp->id,
                'name'       => 'Rahmat Hidayat, S.Pd.',
                'title'      => 'Guru IPA & Koordinator Laboratorium',
                'department' => 'Ilmu Pengetahuan Alam',
                'type'       => 'teacher',
                'bio'        => 'Lulusan Pendidikan Biologi IPB. Mengelola laboratorium IPA dan aktif mengintegrasikan sains berbasis lingkungan dalam pembelajaran.',
                'photo_url'  => $photos['man_2'],
                'email'      => 'rahmat@smp-putrapakuan.sch.id',
                'sort_order' => 6,
                'status'     => 'active',
            ],
            [
                'school_id'  => $smp->id,
                'name'       => 'Herlina Wahyuni, S.E.',
                'title'      => 'Kepala Tata Usaha',
                'department' => 'Administrasi',
                'type'       => 'staff',
                'bio'        => 'Mengabdikan diri di SMP Putra Pakuan selama lebih dari 12 tahun. Dikenal ramah dan profesional dalam mengelola administrasi sekolah.',
                'photo_url'  => $photos['woman_1'],
                'email'      => 'tu@smp-putrapakuan.sch.id',
                'sort_order' => 7,
                'status'     => 'active',
            ],

            // ─── SDIT ──────────────────────────────────────────────────────
            [
                'school_id'  => $sdit->id,
                'name'       => 'Hj. Fatimah Azzahra, S.Ag., M.Pd.',
                'title'      => 'Kepala Sekolah',
                'department' => 'Pimpinan',
                'type'       => 'teacher',
                'bio'        => 'Pendidik senior dengan spesialisasi pendidikan Islam dan manajemen madrasah. Membawa SDIT Putra Pakuan meraih predikat Sekolah Adiwiyata tingkat Kota.',
                'photo_url'  => $photos['woman_4'],
                'email'      => 'kepsek@sdit-putrapakuan.sch.id',
                'sort_order' => 1,
                'status'     => 'active',
            ],
            [
                'school_id'  => $sdit->id,
                'name'       => 'Ustadz Ahmad Farhan, Lc.',
                'title'      => 'Koordinator Program Tahfizh Al-Quran',
                'department' => 'Program Keagamaan',
                'type'       => 'teacher',
                'bio'        => 'Lulusan Universitas Al-Azhar Kairo jurusan Tafsir Al-Quran. Membimbing ratusan siswa dalam program tahfizh intensif sejak 2018.',
                'photo_url'  => $photos['man_3'],
                'email'      => 'tahfizh@sdit-putrapakuan.sch.id',
                'sort_order' => 2,
                'status'     => 'active',
            ],
            [
                'school_id'  => $sdit->id,
                'name'       => 'Neni Kurniasih, S.Pd.',
                'title'      => 'Guru Kelas V & Pembina Olimpiade Sains',
                'department' => 'Sains & Teknologi',
                'type'       => 'teacher',
                'bio'        => 'Guru teladan yang berhasil membimbing siswanya meraih Juara Harapan 1 OSN tingkat Kabupaten 2026. Dikenal sabar dan inovatif dalam menyampaikan materi sains.',
                'photo_url'  => $photos['woman_5'],
                'email'      => 'neni@sdit-putrapakuan.sch.id',
                'sort_order' => 3,
                'status'     => 'active',
            ],
            [
                'school_id'  => $sdit->id,
                'name'       => 'Dewi Lestari, S.Pd.',
                'title'      => 'Guru Tematik Kelas III & Koordinator Kegiatan Kewirausahaan',
                'department' => 'Pendidikan Dasar',
                'type'       => 'teacher',
                'bio'        => 'Pengajar kreatif yang kerap mengintegrasikan proyek nyata dalam pembelajaran. Inisiator kegiatan Market Day SDIT Putra Pakuan yang kini menjadi program unggulan tahunan.',
                'photo_url'  => $photos['woman_2'],
                'email'      => 'dewi.lestari@sdit-putrapakuan.sch.id',
                'sort_order' => 4,
                'status'     => 'active',
            ],
            [
                'school_id'  => $sdit->id,
                'name'       => 'Zainal Abidin, S.Pd.',
                'title'      => 'Guru PJOK & Pembina Ekstrakurikuler Olahraga',
                'department' => 'Pendidikan Jasmani',
                'type'       => 'teacher',
                'bio'        => 'Pelatih olahraga berpengalaman yang aktif membina atletik, renang, dan pencak silat. Membawa siswa binaan meraih medali O2SN tingkat kabupaten.',
                'photo_url'  => $photos['man_4'],
                'email'      => 'zainal@sdit-putrapakuan.sch.id',
                'sort_order' => 5,
                'status'     => 'active',
            ],
            [
                'school_id'  => $sdit->id,
                'name'       => 'Siti Aminah, S.Pd.I.',
                'title'      => 'Guru Pendidikan Agama Islam & Wali Kelas VI-A',
                'department' => 'Keagamaan',
                'type'       => 'teacher',
                'bio'        => 'Pendidik yang memadukan nilai-nilai Islami dengan pendekatan psikologi anak. Aktif mendampingi persiapan MTQ dan kegiatan keagamaan sekolah.',
                'photo_url'  => $photos['woman_6'],
                'email'      => 'siti@sdit-putrapakuan.sch.id',
                'sort_order' => 6,
                'status'     => 'active',
            ],
            [
                'school_id'  => $sdit->id,
                'name'       => 'Hendri Saputra, S.Kom.',
                'title'      => 'Guru TIK & Operator Sekolah',
                'department' => 'Teknologi Informasi',
                'type'       => 'staff',
                'bio'        => 'Mengelola infrastruktur teknologi sekolah termasuk website, aplikasi administrasi, dan laboratorium komputer anak.',
                'photo_url'  => $photos['man_5'],
                'email'      => 'tik@sdit-putrapakuan.sch.id',
                'sort_order' => 7,
                'status'     => 'active',
            ],

            // ─── Yayasan ──────────────────────────────────────────────────
            [
                'school_id'  => $yayasan->id,
                'name'       => 'H. Mujtaba Fauzi, S.H., M.M.',
                'title'      => 'Ketua Yayasan',
                'department' => 'Pimpinan Yayasan',
                'type'       => 'staff',
                'bio'        => 'Memimpin Yayasan Putra Pakuan dengan fokus pada tata kelola, penguatan mutu pendidikan, dan pengembangan jejaring kemitraan.',
                'photo_url'  => $photos['man_1'],
                'email'      => 'ketua@yayasanputrapakuan.or.id',
                'sort_order' => 1,
                'status'     => 'active',
            ],
            [
                'school_id'  => $yayasan->id,
                'name'       => 'Dra. Hj. Siti Rahmawati, M.Pd.',
                'title'      => 'Sekretaris Yayasan',
                'department' => 'Sekretariat',
                'type'       => 'staff',
                'bio'        => 'Mengelola administrasi strategis yayasan, dokumentasi kebijakan, dan koordinasi program lintas unit sekolah.',
                'photo_url'  => $photos['woman_4'],
                'email'      => 'sekretaris@yayasanputrapakuan.or.id',
                'sort_order' => 2,
                'status'     => 'active',
            ],
            [
                'school_id'  => $yayasan->id,
                'name'       => 'Drs. Bambang Suharno, M.B.A.',
                'title'      => 'Bendahara Yayasan',
                'department' => 'Keuangan',
                'type'       => 'staff',
                'bio'        => 'Bertanggung jawab pada perencanaan anggaran, akuntabilitas keuangan, dan penguatan program beasiswa yayasan.',
                'photo_url'  => $photos['man_2'],
                'email'      => 'bendahara@yayasanputrapakuan.or.id',
                'sort_order' => 3,
                'status'     => 'active',
            ],
            [
                'school_id'  => $yayasan->id,
                'name'       => 'Maya Kusumawardani, S.E., M.Ak.',
                'title'      => 'Kepala Divisi Audit Internal',
                'department' => 'Pengawasan Internal',
                'type'       => 'staff',
                'bio'        => 'Memastikan kepatuhan proses keuangan dan operasional yayasan melalui audit berkala dan rekomendasi perbaikan berkelanjutan.',
                'photo_url'  => $photos['woman_2'],
                'email'      => 'audit@yayasanputrapakuan.or.id',
                'sort_order' => 4,
                'status'     => 'active',
            ],
            [
                'school_id'  => $yayasan->id,
                'name'       => 'Arif Rahman Hakim, S.Kom.',
                'title'      => 'Koordinator Transformasi Digital Yayasan',
                'department' => 'Teknologi Informasi',
                'type'       => 'staff',
                'bio'        => 'Mengawal digitalisasi layanan akademik dan administrasi lintas unit agar proses pendidikan lebih efektif, transparan, dan terintegrasi.',
                'photo_url'  => $photos['man_4'],
                'email'      => 'digital@yayasanputrapakuan.or.id',
                'sort_order' => 5,
                'status'     => 'active',
            ],
        ];

        foreach ($staff as $s) {
            TeacherStaff::updateOrCreate(
                ['school_id' => $s['school_id'], 'name' => $s['name']],
                $s
            );
        }
    }
}
